### ISSUE TITLE
Surprising behaviour: argfile reads @argfiles after `--`

### ISSUE THREAD

**Issue by passcod** [rust-cli/argfile#46]
Found in watchexec/watchexec#717.

When there's a `trailing_var_arg` (or in general, really), I would expect that argfile would not parse beyond the `--` separator. That is, these should load an argfile:

```
command @argfile --option
command --option @argfile
command @argfile -- sub args
```

But this should not:

```
command --option -- @bazel-target-or-something
```

Here's a minimal repro:

```rust
#!/usr/bin/env cargo

//! ```cargo
//! [dependencies]
//! argfile = "0.1.6"
//! clap = { version = "4.4.11", features = ["derive"] }
//! ```

use clap::{Parser, ValueHint};

#[derive(Debug, Clone, Parser)]
pub struct Args {
	#[arg(
		trailing_var_arg = true,
		num_args = 1..,
		value_hint = ValueHint::CommandString,
		value_name = "COMMAND",
	)]
	pub command: Vec<String>,
}

fn main() {
    let args = argfile::expand_args(argfile::parse_fromfile, argfile::PREFIX)
		.expect("while reading @argfile");
    let args = Args::parse_from(args);
    dbg!(args);
}
```

Calling with `./repro.rs -- @not-an-argfile` panics, while I would expect it to silently ignore and leave the `@not-an-argfile` in the args.

**Comment by epage** [comment]
`parse_fromfile` is specifically imitating what Python does.  Can you confirm if Python ignore it after an escape (`--`)?

**Comment by passcod** [comment]
It's not exactly the same because Python doesn't have the `--` thing, but for example, with:

```python
import sys
print ('args:', sys.argv)
```

then:

```console
$ python @foo run.py
# parses the foo argfile
args: ['run.py']

$ python run.py @foo
# passes '@foo' literally to the script as argument
args: ['run.py', '@foo']
```

we can see there _is_ a difference in how Python handles `@argfile` depending on where it is relative to the input file

**Comment by passcod** [comment]
Alright if you saw the previous version of this post, didn't realise you were talking about specifically the argparse module from Python; the answer is no, argparse doesn't ignore fromfiles after `--`.

```python
#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser(fromfile_prefix_chars='@')
parser.add_argument('--option')
parser.add_argument('--flag', action='store_true')
parser.add_argument('command', metavar='COMMAND', nargs='+')
print(parser.parse_args())
```

```console
$ ./run.py -- foo
Namespace(option=None, flag=False, command=['foo'])

$ cat foo
--flag

$ ./run.py -- @foo
Namespace(option=None, flag=False, command=['--flag'])
```
