### ISSUE TITLE
Windows path separators lost

### ISSUE THREAD

**Issue by EdVanDance** [rust-cli/argfile#68]
Hello 😃

I'm trying to use this with response files on windows (`features = ["response"]`) with windows style paths in response files. But I'm getting unexpected results.

With ...
```rust
fn main() {
    let args = argfile::expand_args(argfile::parse_response, argfile::PREFIX).unwrap();
    dbg!(args);
}
```

... and this response file ...
```
# response.txt
C:\test\test.rs
```

... I'm getting:
```
     Running `target\debug\argfile-test.exe @response.txt`
[src\main.rs:3:5] args = [
    "target\\debug\\argfile-test.exe",
    "C:testtest.rs",
]
```

The path separators are gone producing an invalid path.

**Comment by epage** [comment]
I believe the problem is we are using `shlex` to do the splitting which is handling the `\` for us.  We'd need something that could split according to Windows splitting rules.

[`wild`](https://crates.io/crates/wild) has some support for this but requires UTF-16 

[`winsplit`](https://crates.io/crates/winsplit) exists but it only works with `&str`.

**Comment by EdVanDance** [comment]
> [`winsplit`](https://crates.io/crates/winsplit) exists but it only works with `&str`.

Could you please elaborate the `&str` aspect?

`parse_response()` is also processing `&str`. Or am I missing something here?

```rust
#[cfg(feature = "response")]
pub fn parse_response(content: &str, _prefix: char) -> Vec<crate::Argument> {
```

**Comment by EdVanDance** [comment]
I just tried using `winsplit`:

```diff
diff --git a/src/response.rs b/src/response.rs
index adabf01..1523ec6 100644
--- a/src/response.rs
+++ b/src/response.rs
@@ -3,8 +3,7 @@
 /// See [Microsoft response files](https://docs.microsoft.com/en-us/cpp/build/reference/at-specify-a-compiler-response-file?view=msvc-170).
 #[cfg(feature = "response")]
 pub fn parse_response(content: &str, _prefix: char) -> Vec<crate::Argument> {
-    shlex::split(content)
-        .unwrap_or_default()
+    winsplit::split(content)
         .into_iter()
         .map(|s| crate::Argument::PassThrough(s.into()))
         .collect()
```

This is the output I'm getting:
```
     Running `target\debug\argfile-test.exe @response.txt`
[src\main.rs:3:5] args = [
    "target\\debug\\argfile-test.exe",
    "#",
    "response.txt",
    "C:\\test\\test.rs",
]
```

Windows path looks good.

I didn't even notice that `shlex` removed the shell style comment 😄  I assume that would actually never appear in a response file.

**Comment by epage** [comment]
Oh right, wasn't paying enough attention to what level things operate at.

**Comment by EdVanDance** [comment]
Awesome. Thank you 😄
